version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
    - echo "Installing cfn-lint..."
    - pip3 install cfn-lint

  pre_build:
    commands:
      - echo "==== WE ARE ENTERED THE PREBUILD STAGE ===="
      - echo "CHECKING THE VERSION OF PYTHON INSTALLED"
      - python3 --version  # Uses python3 explicitly
      - echo "CHECKING IF CFN-LINT WAS INSTALLED"
      - cfn-lint --version

  build:
    commands:
      - echo "==== Build started on `date` ===="
      - echo "CHECKING IF THE TEMPLATE IS PRESENT"
      - ls -l 
      - echo "VALIDATING THE CLOUDFORMATION TEMPLATE"
      - cfn-lint my-ec2-cfn-template.yml
      - echo "BUILDING/PACKAGING THE CLOUDFORMATION TEMPLATE"
      - aws cloudformation package --template-file my-ec2-cfn-template.yml --s3-bucket mysource-bucket-3stages-cicd --output-template-file build-artifact-template.yml
  
  post_build:
    commands:
      - echo "==== Build completed at `date` ===="
    
artifacts:
  files:
    - build-artifact-template.yml